const $=id=>document.getElementById(id);let safetyLatched=false,visibleEvents=[],eventCutoff=0,lastSample=0;
const history=[];const MAX_POINTS=300;
const eventText={bright_light:["强光偷袭","达到L=20，后退半米。"],shake:["受到震动","别晃了，再晃我就罢工。"],feed:["偷偷投喂","这点零食，勉强收下。"],temperature:["温度升高","这么热，还想让我干活。"],voice:["语音命令","听见了，不代表我乐意。"],button:["板载按键","本地交互已触发。"],remote:["STC遥控","第二块STC板正在接管。"],fault:["系统告警","不是我不行，是环境不配合。"]};
function clamp(v){return Math.max(0,Math.min(100,Number(v)||0))}function setMeter(n,v){v=clamp(v);$(n+"Value").textContent=Math.round(v);$(n+"Bar").style.width=v+"%"}
function toast(text,bad=false){const e=$("toast");e.textContent=text;e.style.background=bad?"#ff6f7d":"#8df0c8";e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1800)}
function addSample(t){const stamp=Number(t.received_at)||Date.now()/1000;if(stamp===lastSample)return;lastSample=stamp;history.push({light:Number(t.light_raw)||0,temp:(Number(t.temp_x10)||0)/10,happy:Number(t.happiness)||0,fear:Number(t.fear)||0,x:Number(t.accel_x_mg)||0,y:Number(t.accel_y_mg)||0,z:Number(t.accel_z_mg)||0});if(history.length>MAX_POINTS)history.splice(0,history.length-MAX_POINTS)}
function draw(canvas,series,min,max,threshold){const ratio=devicePixelRatio||1,w=Math.max(300,canvas.clientWidth),h=Math.max(150,canvas.clientHeight);if(canvas.width!==w*ratio||canvas.height!==h*ratio){canvas.width=w*ratio;canvas.height=h*ratio}const c=canvas.getContext("2d");c.setTransform(ratio,0,0,ratio,0,0);c.clearRect(0,0,w,h);c.strokeStyle="rgba(255,255,255,.08)";c.lineWidth=1;for(let i=0;i<=4;i++){const y=12+(h-28)*i/4;c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}if(threshold!==undefined){const y=12+(max-threshold)/(max-min)*(h-28);c.strokeStyle="#ff6f7d";c.setLineDash([5,5]);c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();c.setLineDash([])}series.forEach(s=>{c.strokeStyle=s.color;c.lineWidth=2;c.beginPath();history.forEach((p,i)=>{const x=history.length<2?0:i*w/(MAX_POINTS-1),value=Math.max(min,Math.min(max,s.value(p))),y=12+(max-value)/(max-min)*(h-28);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()})}
function drawCharts(){draw($("environmentChart"),[{color:"#8df0c8",value:p=>p.light},{color:"#ffd36a",value:p=>p.temp}],0,50,20);draw($("emotionChart"),[{color:"#8df0c8",value:p=>p.happy},{color:"#ff6f7d",value:p=>p.fear}],0,100);draw($("accelChart"),[{color:"#ff6f7d",value:p=>p.x},{color:"#8df0c8",value:p=>p.y},{color:"#b99cff",value:p=>p.z}],-2000,2000)}
function motionLabel(m){if(m.status!=="running")return["待命","—",m.reason||"等待动作"];const source=m.source==="windows_stc"?"电脑/STC遥控":(m.source==="stc_remote"?"STC遥控":(m.source==="voice_or_light"?"语音/传感器":"动作执行器"));if(m.direction)return["点动中",source,m.direction+" · 租约 "+(m.lease_ms||300)+" ms"];const r=m.request||{},names={1:"前后移动",2:"原地旋转",3:"横向移动"};return["执行中",source,(names[r.kind]||"动作")+" · #"+(r.motion_id||"—")]}
function updateState(data){const t=data.telemetry||{},m=data.motion||{};addSample(t);drawCharts();safetyLatched=Boolean(data.safety&&data.safety.latched);$("connection").classList.toggle("online",Boolean(data.serial_connected));$("connection").querySelector("span").textContent=data.serial_connected?"STC 在线":"等待 STC";setMeter("happy",t.happiness);setMeter("fear",t.fear);$("lightValue").textContent=t.light_raw??0;$("tempValue").textContent=((Number(t.temp_x10)||0)/10).toFixed(1)+"°C";$("shakeValue").textContent=t.vibration?"受惊":"平稳";$("feedValue").textContent=(t.feed_count??0)+" 次";$("environmentNow").textContent=`L ${t.light_raw??0} · ${((Number(t.temp_x10)||0)/10).toFixed(1)}°C`;$("emotionNow").textContent=`${t.happiness??0} / ${t.fear??0}`;$("accelNow").textContent=`${t.accel_x_mg??0} / ${t.accel_y_mg??0} / ${t.accel_z_mg??0}`;const labels=motionLabel(m);$("motionText").textContent=labels[0];$("motionSource").textContent=labels[1];$("motionDetail").textContent=labels[2];$("motionId").textContent=m.request?.motion_id??m.last_result?.motion_id??"—";const remoteMoving=m.status==="running"&&(m.source==="windows_stc"||m.source==="stc_remote");$("remoteState").textContent=(remoteMoving||t.remote_active)?"正在接管":"未接管";const s=data.safety||{};$("safetyLock").textContent=safetyLatched?"已锁定":"未锁定";$("safetyLock").style.color=safetyLatched?"#ff6f7d":"#8df0c8";$("safetyReason").textContent=s.reason||"未知";$("stopButton").textContent=safetyLatched?"解除急停":"立即急停";$("stopButton").classList.toggle("release",safetyLatched);$("updatedAt").textContent=data.updated_at?new Date(data.updated_at*1000).toLocaleTimeString():"—";if(t.sleeping)$("speech").textContent="终于可以不陪你玩了。";else if((t.fear||0)>=55)$("speech").textContent="谁拿手电筒照我，我走还不行吗。";else if((t.happiness||0)>70)$("speech").textContent="这点零食，勉强收下。";else $("speech").textContent="叫我干嘛，又不是很想理你。"}
function renderEvents(events){events=events.filter(e=>(e.timestamp||0)>eventCutoff);visibleEvents=events;const list=$("events");list.innerHTML="";if(!events.length){list.innerHTML='<li class="empty">等待第一条传感事件……</li>';return}events.slice(0,30).forEach(e=>{const info=eventText[e.name]||[e.name||"未知事件","本宠物拒绝解释。"],li=document.createElement("li");li.innerHTML=`<time>${new Date((e.timestamp||0)*1000).toLocaleTimeString()}</time><span><b>${info[0]}</b><br>${info[1]}</span><em>${e.value??""}</em>`;list.appendChild(li)})}
async function post(path,body){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).error||r.statusText);return r.json()}
async function refresh(){try{const[state,events]=await Promise.all([fetch("/api/state",{cache:"no-store"}),fetch("/api/events",{cache:"no-store"})]);updateState(await state.json());renderEvents(await events.json())}catch(e){$("connection").classList.remove("online");$("connection").querySelector("span").textContent="网页离线"}}
$("stopButton").addEventListener("click",async()=>{try{await post("/api/stop",{engaged:!safetyLatched});toast(safetyLatched?"已请求解除急停":"急停已触发")}catch(e){toast(e.message,true)}});$("clearEvents").addEventListener("click",()=>{eventCutoff=Math.max(Date.now()/1000,...visibleEvents.map(e=>e.timestamp||0));renderEvents([])});addEventListener("resize",drawCharts);refresh();setInterval(refresh,200);
